# This file generates the GitHub Actions matrix.
include:
  - board: nice_nano_v2/zmk
    shield: settings_reset
  - board: nice_nano_v2/zmk
    shield: corne_left
  - board: nice_nano_v2/zmk
    shield: corne_right
