# This file generates the GitHub Actions matrix.
include:
  - board: nrfmicro_13
    shield: settings_reset
  - board: nrfmicro_13
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"LP_Corne\"
    artifact-name: corne_left
  - board: nrfmicro_13
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"LP_Corne\"
    artifact-name: corne_right
